version: '3.8'
services:
  db:
    image: postgres:13
    container_name: tienda_db
    environment:
      POSTGRES_DB: almacen_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secretpassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: